### ISSUE TITLE
دلیگیت

### ISSUE THREAD

**Issue by pooyanaad** [0x4r45h/EigenLayer-node#1]
اقا ممنون از آموزش خوبتون ، من مشکلم اینه با این که steth  تو ولت دارم ، ولی اجازه  دلیگیت رو نمیده
<img width="867" alt="Screenshot 1402-09-24 at 14 19 53" src="https://github.com/0x4r45h/EigenLayer-node/assets/96228003/2e0a37e8-2997-457b-8b67-39e70217cc8a">

**Comment by 0x4r45h** [comment]
باید اول برای [اینجا](https://goerli.eigenlayer.xyz/token/stETH) توکن هات رو re-stake کنی

**Comment by pooyanaad** [comment]
آقا خیلی خیلی ممنون
