### ISSUE TITLE
ارور موقع ثبت اپراتور

### ISSUE THREAD

**Issue by naeim2022** [0x4r45h/EigenLayer-node#2]
سلام وقت بخیر، من موقع ثبت اپراتور همچین اروری می گیرم، می دونید دلیلش چیه؟
<img width="767" alt="s" src="https://github.com/0x4r45h/EigenLayer-node/assets/108026960/ace3b9f8-131d-49b6-b9fe-48e5976639a3">

**Comment by 0x4r45h** [comment]
احتمالا  فایل metadata.json رو  بدرستی آپلود نکردید یا محتواش غلطه

**Comment by naeim2022** [comment]
اون ریپازیتوری که برای آپلود فایل ساخته بودم private بود. پابلیکش کردم درست شد. تشکر.
