### ISSUE TITLE
Installing CLI problem

### ISSUE THREAD

**Issue by EsiNakamoto** [0x4r45h/EigenLayer-node#3]
آرش جان من توی نصب CLI مشکل دارم چه باینری چه از طریق go  چه با make هیچکدوم نشد 
comamnd :curl -sSfL https://raw.githubusercontent.com/layr-labs/eigenlayer-cli/master/scripts/install.sh | sh -s
export PATH=$PATH:~/bin

output: warning: auto completion generation command failed. eigenlayer command completion for bash not installed

**Comment by 0x4r45h** [comment]
این خطا نیست. فقط یه هشداره که اصلا چیز مهمی نیست و نادیده بگیرش و ادامه بده

**Comment by EsiNakamoto** [comment]
خب الان موقع رجیستر کردن میگه 
~# eigenlayer operator register operator.yaml
eigenlayer: command not found
یا برای گرفتن status

**Comment by 0x4r45h** [comment]
این دو تا دستور رو بزن ببین خروجیش چیه. مسیری که داخلش هستی رو نشون میده  
```bash
cd ~
pwd
```
بعد اینو بزن ببین اصلا eigenlayer نصب شده یا نه    
```bash
find / -name eigenlayer   
```


اگه پیداش کنه مسیرش رو مینویسه . خروجی هارو اینجا بزار تا بررسی کنیم

**Comment by EsiNakamoto** [comment]
root@vps86019011:~# pwd
/root
root@vps86019011:~# find / -name eigenlayer
/root/bin/eigenlayer
root@vps86019011:~#

عجیبه کلید ها رو داده بود و ظاهرن نصبه ولی رجیستر و استاتوس نمیده

**Comment by 0x4r45h** [comment]
ببین هر بار که SSH میزنی باید این دستور رو وارد کنی 
```bash
export PATH=$PATH:~/bin
```
اگه میخوای دائمی میشه اینو بزن     
```bash
echo 'export PATH=$PATH:~/bin' >> ~/.bashrc && source ~/.bashrc

```

**Comment by EsiNakamoto** [comment]
بعد رجیستر رو بزنم؟
:~# eigenlayer operator register operator.yaml
2023/12/24 17:04:14 unable to parse file with error &errors.errorString{s:"yaml: line 4: did not find expected key"}

**Comment by 0x4r45h** [comment]
الان مشکل قبلی حل شد.  🎉  
 بنظرم یکبار از اول شروع کن کلید هارو بساز و برو جلو پیچیده نشه
