### ISSUE TITLE
آیا امکان تغییر پسورد فایل BLS هست؟

### ISSUE THREAD

**Issue by abgames410** [0x4r45h/EigenLayer-node#6]
سلام آرش جان اول اینکه ممنونم بخاطر آموزش خوبت
دوم اینکه آرش جان من در پسورد فایل BLS از کاراکتر خاص ")" پرانتز استفاده کردم.
حالا زمانی که میخوام با 
./run.sh opt-in
دستور فایل env. رو ران کنم به ارور
Syntax error: "(" unexpected
حالا با توجه به اینکه فایل BLS با این پسوردی که ")" داخلش هست رمزنگاری شده امکانش هست من پسورد این فایل رو تغییر بدم یا اینکه چه راهکاری براش به ذهنتون میرسه؟ اگه دوباره فایل BLS جدید بسازم میتونم به همین نودی که الان ران کردم اونو اضافه کنم یا نه؟

**Comment by abgames410** [comment]
> سلام آرش جان اول اینکه ممنونم بخاطر آموزش خوبت دوم اینکه آرش جان من در پسورد فایل BLS از کاراکتر خاص ")" پرانتز استفاده کردم. حالا زمانی که میخوام با ./run.sh opt-in دستور فایل env. رو ران کنم به ارور Syntax error: "(" unexpected حالا با توجه به اینکه فایل BLS با این پسوردی که ")" داخلش هست رمزنگاری شده امکانش هست من پسورد این فایل رو تغییر بدم یا اینکه چه راهکاری براش به ذهنتون میرسه؟ اگه دوباره فایل BLS جدید بسازم میتونم به همین نودی که الان ران کردم اونو اضافه کنم یا نه؟

![Screenshot 2024-01-19 133129](https://github.com/0x4r45h/EigenLayer-node/assets/136362471/478a350b-c193-4831-a27f-838d6306c0d7)

**Comment by 0x4r45h** [comment]
سلام. اگه از private key بک آپ داری میتونی فایل های کلید قبلی رو پاک کنی و دوباره ایمپورت کنی با همون اسم. اینبار با پسورد جدید

نحوه ایمپورت اینجا توضیح داده شده 
https://docs.eigenlayer.xyz/operator-guides/operator-installation#import-keys

**Comment by abgames410** [comment]
خیلی ممنونم آرش جان طبق توصیه و آموزش خوب خودت من بک هاپ رو دارم ممنونم ازت
